### ISSUE TITLE
I would like to be able to tell it is working at a glance is a system tray or windows notification possible to state the state when it changes?

### ISSUE THREAD

**Issue by rvcjew** [n4ru/FakeSlice#1]
Great app, but would like a way to see if it is active or not as when it is not I then know I need to go swap back my custom charge threshold as when off it does not seem to revert it, also when active the charge icon does not change (makes sense due to how it works)

Thanks for all the work to make it super simple to take a usb-c pack with me and save my batteries lifespan.

Malcolm

**Comment by n4ru** [comment]
Tooltip has been added in the latest release.

**Comment by rvcjew** [comment]
Thanks, but I don't have the knowledge to compile it myself, will a binary be released with the change at a later date? Edit: saw the build info in Readme. I will try to get a friend who has a working environment do it for me if I can't figure it out.

**Comment by n4ru** [comment]
Binary has already been updated and can be found in the release section.
