### ISSUE TITLE
Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'Plugins.Battery.Think.Native, Version=1.0.6703.7795, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.    at ThinkBattery.Program.Main(String[] args)

### ISSUE THREAD

**Issue by chx** [n4ru/FakeSlice#2]
I ran the supplied DLL copier and then compiled the program with

`\Windows\Microsoft.NET\Framework64\v4.0.30319\csc.exe FakeSlice.cs /r:Lenovo.Modern.Portable.Battery.dll /r:Plugins.Battery.Think.Native.dll`

and also tried

`\Windows\Microsoft.NET\Framework\v4.0.30319\csc.exe FakeSlice.cs /r:Lenovo.Modern.Portable.Battery.dll /r:Plugins.Battery.Think.Native.dll`

and I am getting the error in the title.

Also, the compiled exe looks like 5KB. Is that correct?

**Comment by chx** [comment]
Figured it out. Adding a PR.

**Comment by bulletsponge94** [comment]
I seem to have the exact same problem. How did you resolve it eventually? I don't know what PR means.
